apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: sportpesa-catalog
  description: SportPesa master catalog location
spec:
  targets:
    - https://raw.githubusercontent.com/mofwili/sppesa-monorepo/main/sportpesa-backstage/catalog/org.yaml
    - https://raw.githubusercontent.com/mofwili/sppesa-monorepo/main/sportpesa-backstage/catalog/systems.yaml
    - https://raw.githubusercontent.com/mofwili/sppesa-monorepo/main/sportpesa-backstage/catalog/services.yaml
    - https://raw.githubusercontent.com/mofwili/sppesa-monorepo/main/sportpesa-backstage/catalog/apis.yaml
    - https://raw.githubusercontent.com/mofwili/sppesa-monorepo/main/sportpesa-backstage/scaffolder-templates/go-service-template/template.yaml
    - https://github.com/mofwili/sppesa-monorepo/edit/main/sportpesa-backstage/catalog/all.yaml
